<?xml version='1.0'?>

<robot name="emptyroom_9x9" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="x_dim" value="2.7432" /> <!-- 9ft = 2.7432m -->
  <xacro:property name="y_dim" value="2.7432" />
  <xacro:property name="wall_height" value="0.2" />
  <xacro:property name="wall_thickness" value="0.02" />
  <xacro:property name="exit_width" value="0.5" />
  
  <xacro:include filename="$(find emptyroom_description)/urdf/emptyroom.gazebo" />
  
  <link name='walls'>
    <inertial>
      <mass value="0.837"/>
      <inertia
          ixx="0.0007576" ixy="0" ixz="0"
          iyy="0.0015486" iyz="0"
          izz="0.0017524"
      />
    </inertial>

    <collision name='wall_S_collision'>
      <origin xyz="${x_dim/2} ${-wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${x_dim} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name='wall_S_visual'>
      <origin xyz="${x_dim/2} ${-wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${x_dim} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall_E_collision'>
      <origin xyz="${x_dim+wall_thickness/2} ${y_dim/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_dim} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name='wall_E_visual'>
      <origin xyz="${x_dim+wall_thickness/2} ${y_dim/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_dim} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall_NE_collision'>
      <origin xyz="${x_dim-(x_dim-exit_width)/4} ${y_dim+wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${(x_dim-exit_width)/2} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name='wall_NE_visual'>
      <origin xyz="${x_dim-(x_dim-exit_width)/4} ${y_dim+wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${(x_dim-exit_width)/2} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall_NW_collision'>
      <origin xyz="${(x_dim-exit_width)/4} ${y_dim+wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${(x_dim-exit_width)/2} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name='wall_NW_visual'>
      <origin xyz="${(x_dim-exit_width)/4} ${y_dim+wall_thickness/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${(x_dim-exit_width)/2} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall_W_collision'>
      <origin xyz="${-wall_thickness/2} ${y_dim/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_dim} ${wall_height}"/>
      </geometry>
    </collision>
    <visual name='wall_W_visual'>
      <origin xyz="${-wall_thickness/2} ${y_dim/2} ${wall_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_dim} ${wall_height}"/>
      </geometry>
    </visual>
  </link>
  
</robot>
